// eslint.config.js (flat config)
export default [
  {
    // files/folders ESLint should ignore
    ignores: [
      "build/**",
      ".next/**",
      "node_modules/**",
      "src/aws-exports.js",
      "src/graphql/**", // generated by Amplify
    ],
  },
];
